### PR TITLE
Update splash screen

### PR DESCRIPTION
**Pull request by arcturus2**
### Description of the Change

Integrate the new Constellation logo with the splash screen, inspired by the new NetBeans splash screen.

### CODE REVIEW

**Comment by arcturus2** [comment]
I've got feedback on this and will be proposing some alternatives too.

**Comment by arcturus2** [comment]
I've gotten more options from our designer so it's now time to vote. Please give a thumbs up for which one you like to have your vote count.

**Comment by arcturus2** [comment]
**Current**
original

**Comment by arcturus2** [comment]
**Option 1**
option 1

**Comment by arcturus2** [comment]
**Option 2**
option 2

**Comment by arcturus2** [comment]
**Option 3**
option 3

**Comment by cygnus-x-1** [comment]
> **Option 3**
> option 3

I like the idea of this one, but i'm not satisfied with the details... 
 - I prefer the clearer night sky and the more balanced silhoette
 - emphasising the southern cross stars a little more is good, but they no longer look like stars here (tone them down a little)
 - I prefer the white logo on the dark background (as too much white makes the image feel less calming) but hate that it's not centered in the corner (move it down a little)

**Comment by sol695510** [comment]
> **Option 3**
> option 3

I like this option too and I agree with @cygnus-x-1 points, especially that the Southern Cross's stars just look like circles and not stars.

**Comment by mimosa2** [comment]
I like the option 3. As  @cygnus-x-1 said, the stars need to be clearly visible as option 1.

**Comment by arcturus2** [comment]
> * I prefer the white logo on the dark background (as too much white makes the image feel less calming) but hate that it's not centered in the corner (move it down a little)

Aha! I thought I was being picky so I didn't mention it but totally agree.

**Comment by canis-majoris-42** [comment]
Agree with @cygnus-x-1. Option 3 with a southern cross that stands out but looks more like stars.

**Comment by arcturus2** [comment]
So the majority of you said that you liked option 3 but it needed some changes to be more aligned and to fix the stars. The designer has done this now and it's ready for another review. What do you think?

Constellation-Splash-newstars-1080

**Comment by cygnus-x-1** [comment]
> So the majority of you said that you liked option 3 but it needed some changes to be more aligned and to fix the stars. The designer has done this now and it's ready for another review. What do you think?

Love it. One minor thing i'd suggest is to tint the Southern Cross stars orange (as before) as that aligns with the blue/orange theme Constellation sort of has going on.

**Comment by arcturus2** [comment]
> > So the majority of you said that you liked option 3 but it needed some changes to be more aligned and to fix the stars. The designer has done this now and it's ready for another review. What do you think?
> 
> Love it. One minor thing i'd suggest is to tint the Southern Cross stars orange (as before) as that aligns with the blue/orange theme Constellation sort of has going on.

@cygnus-x-1 would you be OK to try it out with the stars being white for a change? I'm honestly happy with it being less colours given we've gone with a black-ish/white-ish splash screen.

**Pull request merged**
