### PR TITLE
Font improvements

### PR DESCRIPTION
**Pull request by cygnus-x-1**
### Description of the Change

Added ConstellationLabelFonts interface and integrated it with LabelFontsOptionsPanel to allow developers to programmatically set defaults for fonts rendered on a graph.

Updated the "Show in New Table View" context menu to actually show the selection in the Table View, rather than just open it.

Added a default arrangement to the Icon Graph builder to avoid all the nodes being rendered on top of each other.

### Alternate Designs

N/A

### Why Should This Be In Core?

These  changes all provide for a better user experience.

### Benefits

N/A

### Possible Drawbacks

N/A

### Verification Process

Exploratory testing.

### Applicable Issues

N/A

### CODE REVIEW

**Comment by aldebaran30701** [comment]
I seem to be getting some odd behaviour with labels. 
I went to settings, constellation tab, font labels tab, changed the font to Yu gothic ui semibold and now my labels are appearing with missing segments. rotating the graph does nothing to fix this.
image
image
image

**Comment by aldebaran30701** [comment]
`
java.lang.ArrayIndexOutOfBoundsException: 9712
	at au.gov.asd.tac.constellation.visual.opengl.utilities.glyphs.GlyphRectangleBuffer.addRectImage(GlyphRectangleBuffer.java:212)
	at au.gov.asd.tac.constellation.visual.opengl.utilities.glyphs.GlyphManagerBI.lambda$renderTextAsLigatures$5(GlyphManagerBI.java:400)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at au.gov.asd.tac.constellation.visual.opengl.utilities.glyphs.GlyphManagerBI.renderTextAsLigatures(GlyphManagerBI.java:393)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.batcher.NodeLabelBatcher.bufferBottomLabel(NodeLabelBatcher.java:228)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.batcher.NodeLabelBatcher.fillBottomLabels(NodeLabelBatcher.java:214)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.batcher.NodeLabelBatcher.createBatch(NodeLabelBatcher.java:158)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.GraphRenderable.lambda$getChangeProcessor$3(GraphRenderable.java:160)
	at au.gov.asd.tac.constellation.visual.display.VisualProcessor.lambda$null$1(VisualProcessor.java:296)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at au.gov.asd.tac.constellation.visual.display.VisualProcessor.lambda$processChangeSet$2(VisualProcessor.java:295)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at au.gov.asd.tac.constellation.visual.display.VisualProcessor.processChangeSet(VisualProcessor.java:293)
	at au.gov.asd.tac.constellation.visual.display.VisualProcessor.lambda$update$0(VisualProcessor.java:206)
[catch] at java.lang.Thread.run(Thread.java:748)
`

Occurred when minimizing the window of a graph causes this error. Graph was built using sphere graph builder. 

Also I didn't seem to notice any section which had their font changed to the current selection. It all looked default.

**Comment by formalhaut69** [comment]
image
Just something small but when you click add font and then click add script, the language will be added to the following line. I think it should be adding it to the same line. I also couldn't get the font to change.

**Comment by formalhaut69** [comment]
image
If you have one node selected when you select the icon graph builder, the nodes will be rendered on top of each other.

**Comment by arcturus2** [comment]
> As mentioned, can't get the fonts to change.

After saving the change, can you close and open Constellation to see if it makes a difference?

**Comment by cygnus-x-1** [comment]
Thanks for all the feedback guys.

> I went to settings, constellation tab, font labels tab, changed the font to Yu gothic ui semibold and now my labels are appearing with missing segments. rotating the graph does nothing to fix this.

Weird... however I can't reproduce it. Perhaps this is a gpu-specific issue? @arcturus2 thoughts?

> Occurred when minimizing the window of a graph causes this error. Graph was built using sphere graph builder.

I also couldn't make this happen, but I might have been doing it wrong. What do you mean by minimizing the graph window? Did you minimise the application, or minimize a floating graph pane, or something else?

> Just something small but when you click add font and then click add script, the language will be added to the following line.

Most of this PR is built on top of @algol60's work - I really just improved how default label values work. While both the 'Add' buttons insert at the current cursor position, the 'Add Font' button also adds a new line whereas the 'Add Script' button does not which is why you're seeing this behaviour. If you do not add a new line after adding a font, then you need to manually add new lines in the text area. I think the UI here should be redesigned (and I have mentioned this to @algol60), but for now I could remove the 'Add Script' button and instead include the script dropdown as part of adding a font.

> As mentioned, can't get the fonts to change.

It looks like the font only changes after restarting the app. I will add a warning to the UI to make this clear.

> If you have one node selected when you select the icon graph builder, the nodes will be rendered on top of each other.

This is standard behaviour for all arrangements, and so will affect all instances where an arrangement plugin is called (such as after data access view plugins). If we want to fix this it'll require more thought and a larger change.

**Comment by aldebaran30701** [comment]
@cygnus-x-1 
It is not a 100% replication rate; I managed to narrow it down to either switching between two graphs, and also when the graph was resized by opening the new table view or even a mix of that and the attribute editor. The resize or reload seemed to trigger the labels reloading in that manner. 
Switch between the graphs a few times, open the new table view intermittently and it will occur. It's the second pc i've had it occur on

Regarding the reload of the application, It appears that it probably is the cause; I faced the same issue with blaze size preferences.

**Comment by formalhaut69** [comment]
@cygnus-x-1 @arcturus2 Okay, I was able to get the font to change after closing and re opening constellation. I'm not sure what the scripts are meant to do or how to get them to work though. Is someone able to give me a brief explanation? thanks.

**Comment by arcturus2** [comment]
> > I went to settings, constellation tab, font labels tab, changed the font to Yu gothic ui semibold and now my labels are appearing with missing segments. rotating the graph does nothing to fix this.
> 
> Weird... however I can't reproduce it. Perhaps this is a gpu-specific issue? @arcturus2 thoughts?

@aldebaran30701 can you please paste the output from Help -> Show JOGL Version?

@algol60 it would be good to get your thoughts on this too.

**Comment by cygnus-x-1** [comment]
I've made the changes described above... and a couple of others >_> I may have gone down a rabbit hole updating docs and image references.

I still haven't been able to replicate the "labels with missing segments" issue, however I did see the other issue @aldebaran30701 mentioned above once (although only after closing the app?). @algol60  - would you mind taking a look into that?

@formalhaut69 - the scripts are used to limit a font to specific unicode script blocks, as in you might want to use SansSerif for Latin characters and Ariel for Arabic or something like that. It's explained within ```LabelFontsOptionsPanel.descriptionTextArea```.

**Comment by aldebaran30701** [comment]
[JOGL Version.txt](https://github.com/constellation-app/constellation/files/4131280/JOGL.Version.txt)

**Comment by arcturus2** [comment]
Thanks for that @aldebaran30701. The interesting lines are:

```
OpenGL version: 4.5.0 NVIDIA 398.36
Vendor: NVIDIA Corporation
Renderer: Quadro P1000/PCIe/SSE2
```

Looking at the output it looks like the driver on that PC is version `398.36` I did a search on the NVIDIA site and there is a newer version available which is `441.66`. Is there any chance you could have the new version installed and test it again?

The link should be https://www.nvidia.com/Download/driverResults.aspx/155848/en-us and I went to the website and filtered on Quadro Series -> P1000.

**Comment by arcturus2** [comment]
Just letting everyone know that I changed the destination branch from `master` to `new-fonts` so that @algol60 could continue making additions.

Though this branch has been "merged" the discussions and feedback from @aldebaran30701 and @formalhaut69  should continue here please.

**Comment by algol60** [comment]
> `java.lang.ArrayIndexOutOfBoundsException: 9712 at au.gov.asd.tac.constellation.visual.opengl.utilities.glyphs.GlyphRectangleBuffer.addRectImage(GlyphRectangleBuffer.java:212)

This is reproducible by creating a sphere graph with 1000 nodes and checking the "All displayable chars" box. The texture coordinates array was being reset whenever a new font texture page was being created, instead of being left to grow. Fixed.

**Comment by arcturus2** [comment]
This issues raised in this PR have been fixed by @algol60 and it will be great to get another review and test verification everything is working. Please see #222.

**Comment by aldebaran30701** [comment]
Even after updating to the most recent JOGL version, I can still replicate the issue of missing sections of labels. 
Switch between two graphs which have sphere graphs built, I also had the new table view opened. I switched maybe 4-5 times and the labels became messed up.

**Comment by arcturus2** [comment]
@aldebaran30701 thank you for the clarification. It's good to confirm that the issue is with our code.

Are you able to pull the latest changes in the `new-fonts` branch and test is again? The new PR is #222.

**Comment by aldebaran30701** [comment]
> @aldebaran30701 thank you for the clarification. It's good to confirm that the issue is with our code.
> 
> Are you able to pull the latest changes in the `new-fonts` branch and test is again? The new PR is #222.

I've done so, and commented on both issues as it was relevant to both. I checked out the most recent PR in #222

**Pull request merged**
