### PR TITLE
Updated Import Database help doco

### PR DESCRIPTION
**Pull request by Guilty-Spark-343**
### Description of the Change

Changed the help doco to better reflect the new features with import database.
Added instructions for adding a new driver including where to find the jars and how to create a connection using the new driver including the connection strings.

There were a few images used to demonstrate usage.
DBDriversExample
Constellation_db_connections
ImportDatabaseFullExample

### Applicable Issues

#1324

### CODE REVIEW

**Comment by Guilty-Spark-343** [comment]
thanks for the review :) , I made those changes and pushed them

**Comment by arcturus2** [comment]
@Guilty-Spark-343 so we merged in our new help system which is in markdown and we couldn't merge your PR in sooner as we put a temporary hold on help updates. I really would like to include this PR in now so I have gone and made the  change to the markdown file equivilent. If you delete the html file that is conflicting and use the attached markdown file along with your images I think it should be fine.

[import-from-database.md](https://github.com/constellation-app/constellation/files/7471853/import-from-database.md)

**Comment by Guilty-Spark-343** [comment]
Sorry I never got back to this one...  It looks like you've fixed this one up so I'll close the PR.

**Comment by antares1470** [comment]
Hi @Guilty-Spark-343, don't think we actually got around to adding your changes so we can still review them if you'd like.
Basically we switched over the our help system just after you added your PR and so we were needing to migrate your changes to that new system.

@arcturus2 converted your help page into markdown so if you find the existing markdown file and overlay your changes (from the markdown version) onto the existing file and add the images to the resources folder, it should be good to go.

Note the help pages (and images) are now all located in the release/modules/ext folders of the respective modules (not in src)

**Pull request closed without merging**
