### PR TITLE
Commit the latest project.xml file

### PR DESCRIPTION
**Pull request by arcturus2**
### Description of the Change

* Ran update dependencies clean build. Just want to get this into the code base as it keeps coming up as a diff.

### CODE REVIEW

**Comment by arcturus2** [comment]
Is anyone else getting this or is it just me? If it's just me then happy to close this PR as won't do.

**Comment by aldebaran30701** [comment]
@arcturus2 I'm also getting this, It appeared when I merged master back into the importer view branch. I didn't want to commit it as the dependencies were going backwards. I still don't actually understand why they would be doing so.. ?

**Comment by formalhaut69** [comment]
I think this used to come up for me when I update dependencies clean and build but I did it just now and it didn't come up in my changes.

**Comment by formalhaut69** [comment]
I swapped to your branch this branch @arcturus2 and then updated dependencies clean and built and it tried to change the Jar back 1.1.14
image

**Comment by arcturus2** [comment]
Yeah this reminds me @formalhaut69 we discussed this exact problem; so now I'm having the problem you did before. So strange.

**Comment by formalhaut69** [comment]
@arcturus2 yeah it stopped coming up for me recently and the only thing that's changed is that I reinstalled github desktop because my branches kept breaking 😕

**Comment by arcturus2** [comment]
Thanks for the feedback @formalhaut69

**Pull request closed without merging**
