### PR TITLE
Importer improvements

### PR DESCRIPTION
**Pull request by antares1470**
### Prerequisites

- [ ] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first.

### Description of the Change

Changes made recently to allow the filter in the file and db importers to work from the get go meant that the importers were now taking a lot longer to load (this includes application load time if an importer was open at the end of a previous session). I've reverted that change so that the speed of loading is now back.

This means the filter is no longer available from the get go so I've added in some changes to help with that. Firstly changed the prompt text in the filter box to indicate it is unavailable and then switches to the current prompt text once it becomes available. I then made changes so that the the process for loading the filter happens from app startup rather than when an importer is opened.

### Why Should This Be In Core?

In this case speed difference is significant enough that it is preferred to the filter being available from the get go. UX improvements around that then are more helpful for the user

### Benefits

Importers don't take forever to load, users more informed about filter availability

### Possible Drawbacks

The obvious one is the filter isn't available from the get go. Hopefully the UX improvements in here though help the user understand better what is going on.

### Applicable Issues

#1426

### CODE REVIEW

**Comment by antares1470** [comment]
@Auriga2 did you get that with the most recent version of the branch? The exception you saw was one I saw early on but haven't encountered since this commit I made: https://github.com/constellation-app/constellation/pull/1502/commits/2344134f31b7c1e2cdc195e7813af27c78f470f0

**Comment by Auriga2** [comment]
Ah yes, I checked out the branch today but somehow didn't have the latest version!

**Comment by Auriga2** [comment]
Not sure whether it's related to your changes, but I get this exception when importing to a `New Bare Graph`:
image

```
java.lang.ArrayIndexOutOfBoundsException
Caused: java.lang.RuntimeException
	at au.gov.asd.tac.constellation.plugins.templates.SimpleEditPlugin.run(SimpleEditPlugin.java:135)
	at au.gov.asd.tac.constellation.graph.node.plugins.DefaultPluginEnvironment.executePluginNow(DefaultPluginEnvironment.java:237)
	at au.gov.asd.tac.constellation.plugins.PluginExecutor$PluginEntry.executeNow(PluginExecutor.java:406)
	at au.gov.asd.tac.constellation.plugins.PluginExecutor$1.execute(PluginExecutor.java:256)
	at au.gov.asd.tac.constellation.plugins.templates.SimplePlugin.run(SimplePlugin.java:68)
[catch] at au.gov.asd.tac.constellation.graph.node.plugins.DefaultPluginEnvironment.lambda$executePluginLater$0(DefaultPluginEnvironment.java:130)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by antares1470** [comment]
> Should we log a new ticket to handle that?

@Auriga2 Possibly could but I personally don't think it will be worthwhile at this stage. I think the issue stems more from the Bare Graph itself rather than how it is handled. While a Bare graph in theory sounds good, you realise that there are some attributes that it wouldn't make sense to go without anyway. I think then it is probably more a review of the bare graph that needs to be done rather instead of handling it properly, but I'm not sure that is worth a ticket at present

**Comment by antares1470** [comment]
> Should we log a new ticket to handle that?

@Auriga2 Possibly could but I personally don't think it will be worthwhile at this stage. I think the issue stems more from the Bare Graph itself rather than how it is handled. While a Bare graph in theory sounds good, you realise that there are some attributes that it wouldn't make sense to go without anyway. I think then it is probably more a review of the bare graph that needs to be done rather instead of handling it properly, but I'm not sure that is worth a ticket at present

**Comment by antares1470** [comment]
> Should we log a new ticket to handle that?

@Auriga2 Possibly could but I personally don't think it will be worthwhile at this stage. I think the issue stems more from the Bare Graph itself rather than how it is handled. While a Bare graph in theory sounds good, you realise that there are some attributes that it wouldn't make sense to go without anyway. I think then it is probably more a review of the bare graph that needs to be done rather instead of handling it properly, but I'm not sure that is worth a ticket at present

**Pull request merged**
