### PR TITLE
Changed data access view icon

### PR DESCRIPTION
**Pull request by Atlas139mkm**
### Description of the Change

Small and quick change.
- Changed the data access icon to the one suggested in #1407
image

### Why Should This Be In Core?

Eye ball was intimidating and the chart makes more sense.

### Benefits
 
UI UX

### Verification Process

All buttons still work as intended, just changed the image

### Applicable Issues

#1407

### CODE REVIEW

**Comment by arcturus2** [comment]
@Atlas139mkm thank you for working on this straight away and @GammaVel thank you for the suggestion and even the icon. For me though I am not convinced the bar graph icon is the right fit. To me it does not explain that the data access view is able to query data.

**Review by arcturus2 — CHANGES_REQUESTED** [review]
I'm not sure about this icon.

**Comment by Atlas139mkm** [comment]
All good, I'll see if I can find a more fitting one that portrays the message of querying data.

**Comment by Atlas139mkm** [comment]
Here are a couple of options I have looked at.
1
image
2
image
3
image
4
image

I figured the magnify glass indicated querying a bit more.
Let me know your thoughts @arcturus2 @GammaVel  1,2,3 or 4?

**Comment by arcturus2** [comment]
@Atlas139mkm @GammaVel I've had a bit of a rethink and this icon is warming up to me so I am OK to merge this PR in as its way better than the eye!

**Comment by GammaVel** [comment]
Nice work @Atlas139mkm and @arcturus2 !  I definitely think it is better than the eye. It just occurred to me that a key might have been good too as I like to use this view to unlock my data. Maybe next time!

**Pull request merged**
