### PR TITLE
Layers view heading alignments

### PR DESCRIPTION
**Pull request by aldebaran30701**
### Description of the Change
Align headings of layers view UI

### Alternate Designs
N/A

### Why Should This Be In Core?
Displays correctly now

### Benefits
Easier usage

### Possible Drawbacks
N/A

### Verification Process
Test multiple view positions

### Applicable Issues
#223

### CODE REVIEW

**Comment by arcturus2** [comment]
Nice work @aldebaran30701. I'm going to merge this in with the v2 beta I am just about to publish so merging it in. I did notice that the 2nd column "Visibility" doesn't stretch like the others so on my laptop its showing as "Visib...".

**Comment by cygnus-x-1** [comment]
Good stuff - longer term i think you should make the `layers` a GridPane and have common alignment for the headings and layer info that way.

**Comment by aldebaran30701** [comment]
> I did notice that the 2nd column "Visibility" doesn't stretch like the others so on my laptop its showing as "Visib...".

I had a look with scaling on windows, but couldn't get it to happen. I can add some extra padding to allow for devices with higher or lower res if that is what would have caused that. 
resize

**Comment by arcturus2** [comment]
It might be isolated to Linux then given this is from my Linux laptop

Peek 2020-04-16 16-45

**Pull request merged**
