### PR TITLE
various-minor-fixes

### PR DESCRIPTION
**Pull request by cygnus-x-1**
### Description of the Change

:art: minor layout improvements to various options panes to reduce empty space.
:art: added missing module descriptions for new modules (welcome, what's new, notes).
:memo: updated the "getting started" script in the scripting view to make it more efficient for large graphs.
:arrow_up: updated various dependencies to the latest versions (geotools, apache-poi, jackson, controlsfx).

### CODE REVIEW

**Comment by arcturus2** [comment]
I will approve it because its a minor issue but App font is overflowing

image

**Review by arcturus2 — APPROVED** [review]

**Comment by antares1470** [comment]
> I will approve it because its a minor issue but App font is overflowing
> 
> image

@arcturus2 as an FYI this is occurring in master as well so I don't think the issue is with this branch

**Review by antares1470 — APPROVED** [review]
Once the merge conflicts are resolved this should be good to go

**Comment by cygnus-x-1** [comment]
> I will approve it because its a minor issue but App font is overflowing
> 
> image

Fixed this and the merge conflicts.

**Pull request merged**
