### PR TITLE
Fix the NoSuchMethodException when loading certain Templates in the DAV

### PR DESCRIPTION
**Pull request by Auriga2**
### Prerequisites

- [x] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first.

### Description of the Change
Fixed the `NoSuchMethodException` when loading a Template with any `Graph element type` in the `Test Parameters` plugin in the Data Access View.

### Why Should This Be In Core?
Bug Fix

### Benefits
No exceptions are thrown

### Verification Process
Open data access view and select few parameters from Test parameters plugin including `Graph Element Type`

Select Workflow Options -> Save Templates and save the file

Right click and Select Deactivate all plugins to clear the selections.

Select Workflow Options -> Load Templates and open the file in step 2 and verify no exceptions are thrown, and all the fields are populated including `Graph Element Type`

### Applicable Issues

https://github.com/constellation-app/constellation/issues/1488

### CODE REVIEW

**Comment by Auriga2** [comment]
None of the constructors available are matching because the GraphElementTypeParameterValue is an inner class and the outer class TestParametersPlugin is also included as a constructor parameter by default in each constructor.
image

**Comment by Auriga2** [comment]
@antares1470  Fixed the test parameters plugin by making the `GraphElementTypeParameterValue` a static nested class.
Also added a comment in SingleChoiceParameterValue to avoid future issues. We might get the same issue with MultiChoiceParameterValues. I'll add a comment there as well if you think is required.

**Comment by antares1470** [comment]
> @antares1470 Fixed the test parameters plugin by making the `GraphElementTypeParameterValue` a static nested class. Also added a comment in SingleChoiceParameterValue to avoid future issues. We might get the same issue with MultiChoiceParameterValues. I'll add a comment there as well if you think is required.

@Auriga2 I wouldn't say it is "required" might if you reckon there will be a similar issue for multi choice parameters then I think it would be nice to include a similar comment there as well

**Review by antares1470 — APPROVED** [review]
You could add to the multi choice parameters as you mentioned but looks good otherwise

**Review by antares1470 — CHANGES_REQUESTED** [review]
Sorry I overlooked something, it appears there are some unit tests failing. If you're able to check those out, that would be great

**Review by antares1470 — APPROVED** [review]

**Review by antares1470 — APPROVED** [review]

**Review by arcturus2 — APPROVED** [review]

**Pull request merged**
