### PR TITLE
Check import definitions and if positional values are found (ie: x, y…

### PR DESCRIPTION
**Pull request by serpens24**
### Description of the Change

Check import definitions and if positional values are found (ie: x, y, z) then prevent auto arrangers kicking in. If no positional information exists, then allow auto arrangers to operate.

### Alternate Designs

Considered where check for position should be made - however found this to be the only real option.

### Why Should This Be In Core?

Requested bug fix

### Benefits

Allow positional values imported be used to render node positions

### Possible Drawbacks

If a user imports nodes with positional data but then imports transactions with no positional information, the auto arranger kicks in. This has been agreed with @arcturus2  as acceptable.

### Verification Process

Imported nodes with no positions - confirmed auto arranger kicked in.
Imported nodes with just X set - confirmed a horizontal line of nodes displayed.
Imported nodes with just Y set - confirmed a horizontal line of nodes displayed.
Imported nodes with just Z set - confirmed nodes stacked back in the Z dimension and can be seen when middle click panning.
Imported nodes with full X, Y - confirmed nodes displayed at correct locations.
Imported transactions with no positions - confirmed auto arranger kicked in and redrew all of graph.
Imported transactions with positions - nodes displayed at correct locations.

### Applicable Issues

See above.

### CODE REVIEW

**Comment by arcturus2** [comment]
@cygnus-x-1 I'd be keen for your review of this if you have time?

**Comment by cygnus-x-1** [comment]
Seems reasonable to me, although you should replace the magix "x", "y" and "z" strings with VisualConcept.VertexAttribute.X, VisualConcept.VertexAttribute.Y and VisualConcept.VertexAttribute.Z.

**Comment by serpens24** [comment]
Thanks. I wasnt aware of the Visualconcept class. I'll look to pull that in.

**Comment by serpens24** [comment]
I made a mistake with my second commit ... I hadnt saved the changes to destination, so adding another commit to fix.

**Comment by arcturus2** [comment]
No worries @serpens24 can you send through a PR and I'll merge it in.

**Pull request merged**
