### PR TITLE
Notes View "Remove Selected" Menu Item Disabled

### PR DESCRIPTION
**Pull request by altair1673**
### Prerequisites

- [X] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change
When a note is not associated with any vertexes or transactions the "Remove Selected" option is the context menu is disabled.

### Why Should This Be In Core?
Reduces confusion on notes associated with the whole graph when the "remove selected" option does nothing.

### Benefits
Improves suability

### Verification Process
When no graph elements are associated with note the "Remove Selected" option is disabled. When I add elements to the note the option becomes enabled again.

### Applicable Issues
#1249

### CODE REVIEW

**Review by antares1470 — CHANGES_REQUESTED** [review]
Are you also able to disable the add selected option as well? When a note applies to the graph, any subsequently added nodes and transaction are added to the note, and hence add selected is also redundant

**Comment by Delphinus8821** [comment]
> Are you also able to disable the add selected option as well? When a note applies to the graph, any subsequently added nodes and transaction are added to the note, and hence add selected is also redundant

@antares1470 I believe with the way it was written, if a note was applied to the graph and then the user added nodes or transactions to it, it changed the note from being one applied to the graph to being one only applied to those newly added selected elements.

**Comment by antares1470** [comment]
> @antares1470 I believe with the way it was written, if a note was applied to the graph and then the user added nodes or transactions to it, it changed the note from being one applied to the graph to being one only applied to those newly added selected elements.

So I can't recall exactly how it's being stored under the hood but if I select the whole graph and then add a user note, if it is applied to selected it specifies as being applied to x nodes and y transactions and if not it specifies being applied to the graph. If I then add a node to the graph, the note that applies to the selection won't include this new node whereas the one applied to the graph does. See the gif below demonstrating this:

notesViewSelectOnGraph

**Comment by Delphinus8821** [comment]
> > @antares1470 I believe with the way it was written, if a note was applied to the graph and then the user added nodes or transactions to it, it changed the note from being one applied to the graph to being one only applied to those newly added selected elements.
> 
> @Delphinus8821 So I can't recall exactly how it's being stored under the hood but if I select the whole graph and then add a user note, if it is applied to selected it specifies as being applied to x nodes and y transactions and if not it specifies being applied to the graph. If I then add a node to the graph, the note that applies to the selection won't include this new node whereas the one applied to the graph does. See the gif below demonstrating this:
> 


@antares1470 This is a different case to when you use the 'Add Selected' button on the note. A note that is applied to a graph will always be applied to the whole graph but if the user uses the 'Add Selected' button, then the selection applied to the note updates. See the gif demonstration below:
NotesAdd

**Comment by antares1470** [comment]
> @antares1470 This is a different case to when you use the 'Add Selected' button on the note. A note that is applied to a graph will always be applied to the whole graph but if the user uses the 'Add Selected' button, then the selection applied to the note updates.

@Delphinus8821 Ok I didn't realise that was a thing, my bad there.

That being said, I would argue that what is being demonstrated there isn't "Add Selected" but instead something like "Change to Selected". When I see "Add Selected", I think of appending to the existing selection for the note, rather than replacing. This is certainly the case where if you have a note that applies to 1 node and you then select a different node (with the node the note is applied to de-selected) and add selected, the note is now applied to 2 nodes. So in the case of a note being applied to the whole graph, there isn't anything you can append to the note that isn't already applied.

Consequently, I actually think "Add Selected" for the note applied to the whole graph is misleading and therefore should still be disabled. There may be an argument for including an option to change the selection instead but I note that currently in master that while "Add Selected" will change the note selection to the selected graph elements, "Remove Selected" doesn't do the opposite, i.e. change the selection to everything bar the selected graph elements (presumably because of the way a note is stored).

**Review by antares1470 — APPROVED** [review]

**Review by Delphinus8821 — APPROVED** [review]

**Pull request merged**
