### PR TITLE
:bug: Delete handleNewGraph from ComponentShowing

### PR DESCRIPTION
**Pull request by Nova-2119**
Previously when the Scatterplot view was opened no listener would be
created because componentShowing would update the currentGraph prior to
the code that check if the currentGraph has changed and creates a
listener if it has. This led to the scatterPlot view being 
unresponsive.

### Benefits

Scatterplot updates as expected

### Possible Drawbacks

As of yet unseen consequence from code removal

### Applicable Issues

https://github.com/constellation-app/constellation/issues/794

### CODE REVIEW

**Review by aldebaran30701 — APPROVED** [review]
This seems to be an oversight in my testing from stopping refreshes on views which are minimized.
Good spotting!

**Review by arcturus2 — CHANGES_REQUESTED** [review]
The issue with removing the `onShowing` is that when the view is docked and you hover over it, it no longer picks up the graph that you are on. See the gif.

pr 802 issue in docked mode

Secondly @Nova-2119 can you try to sort out your LF with git settings as files your modifying come up as all lines being changed. Thanks!

**Comment by Nova-2119** [comment]
@arcturus2 apologies, I only just saw your comment. I will get onto this next week.

**Comment by Nova-2119** [comment]
> 
> 
> The issue with removing the `onShowing` is that when the view is docked and you hover over it, it no longer picks up the graph that you are on. See the gif.
> 
> pr 802 issue in docked mode
> 
> Secondly @Nova-2119 can you try to sort out your LF with git settings as files your modifying come up as all lines being changed. Thanks!

Awesome, so Im fairly confident I have fixed this. I added the onShowing method back in and got it to trigger a refresh rather than handle new graph. This way it updates in the scenario above but doesn't update the activeGraph (the original problem). 
When you open a graph and then open the scatterplot it will perform a refresh with a null graph (which refresh is fine with) before then updating the active graph and refreshing the plot again. The first refresh is therefore redundant, but I don't see a way around it, we need that refresh for the scenario above, and we have no way of distinguishing the two scenarios.

When the view is docked and you switch graphs ListeningTopComponent.newActiveGraph() is called which will update ScatterPlotTopComponent.currentGraph but wont refresh the graph. This means that everything is setup and you just need to refresh the view when the view is shown. Previously we called handleNewGraph() which was overkill because that is already called when the graph is switched, its also what caused the original issue by updating currentGraph prior to calling ListeningTopComponent.newActiveGraph() and hence stopping listeners being created.

**Review by arcturus2 — APPROVED** [review]
Nice work @Nova-2119

**Review by antares1470 — APPROVED** [review]

**Pull request merged**
