### PR TITLE
Unfocus Plugin Swing Dialog Ok Button v2

### PR DESCRIPTION
**Pull request by antares1470**
### Description of the Change

When a plugin is run interactively, checks whether a multi-line string parameter exists and unfocuses ok button of swing dialog if so.

### Alternate Designs
#762 

### Benefits

Allows users to hit enter when typing things into a multi-line string parameter via the swing dialog box 

### Applicable Issues

#757

### CODE REVIEW

**Comment by aldebaran30701** [comment]
I like this change better than #762.

**Review by arcturus2 — APPROVED** [review]
I'd prefer this over #762

**Comment by cygnus-x-1** [comment]
I think this implementation is much neater, and should be easy to update to the more flexible solution we previously discussed if we decide to go down that route.

**Comment by antares1470** [comment]
Based on feedback, I'm going to keep this one and close #762

**Pull request merged**
