### PR TITLE
New Constellation logo

### PR DESCRIPTION
**Pull request by arcturus2**
### Description of the Change

* Replaced the existing logo files with the new Constellation logo
* Renamed the shortcuts folder to distribution and added the pre-build exe with the Constellation logo

### Alternate Designs

Various designs were proposed and this was the winning combination based on a vote from the user community.

### Benefits

Now that Constellation is shared with the world it is time to give it a new look at feel, starting with the logo.

### Possible Drawbacks

I've included the .exe files to version control because they have been updated to include the new Constellation icon. Perhaps when we get Travis integrated we can remove them and instead do something like:

```console
apt-get install wine-core.i686
wget http://www.rw-designer.com/rsrc/ReplaceVistaIcon.exe
wine ReplaceVistaIcon.exe constellation.exe Constellation.ico
wine ReplaceVistaIcon.exe constellation64.exe Constellation.ico
```

### CODE REVIEW

**Comment by arcturus2** [comment]
@cygnus-x-1 you haven't accepted my invite so I can't add you as a reviewer yet. Happy for you to review this PR too.

**Comment by cygnus-x-1** [comment]
> @cygnus-x-1 you haven't accepted my invite so I can't add you as a reviewer yet. Happy for you to review this PR too.

I have now :)

**Comment by cygnus-x-1** [comment]
Additionally, the icon looks fairly undefined in the taskbar, and even more so in the application (at least on my 1080p monitors).

icon_01

icon_02

As we previously discussed, I thought this might be the case as the icon is quite complex in shape. However, I think this is being exacerbated by providing Netbeans a high resolution icon (1800 x 1800) and having it downscale on the fly.

**Comment by arcturus2** [comment]
> I'm seeing some odd warnings on build:
> _Warning: stray file D:\projects\constellation\branding\Constellation_Application_Icon.png encountered; ignoring Warning: stray file D:\projects\constellation\branding\Constellation_logo.ai encountered; ignoring Warning: stray file D:\projects\constellation\branding\Constellation_Logo.png encountered; ignoring Warning: stray file D:\projects\constellation\branding\Constellation_Logo_and_Title.png encountered; ignoring Warning: stray file D:\projects\constellation\branding\Constellation_SplashScreen_1920x1080.jpg encountered; ignoring Warning: stray file D:\projects\constellation\branding\Constellation_SplashScreen_1920x1200.jpg encountered; ignoring_
> 
> Is this expected?

Good catch @cygnus-x-1. I've moved the files to a `logo` folder.

**Comment by arcturus2** [comment]
> However, I think this is being exacerbated by providing Netbeans a high resolution icon (1800 x 1800) and having it downscale on the fly.

I can see why you assumed this @cygnus-x-1 but I can confirm that the application icon NetBeans is using isn't the file `Constellation_Application_Icon.png`. That is a high resolution image of the icon to be used on a t-shirt or billboard 😄 in the future.

Each frame*.gif or frame*.png image created in `branding\core\core.jar\org\netbeans\core\startup` were created from the original .ai each time to make sure the maximum quality was retained (i.e not resizing images from high res to low).

The icons being used on my screen at least are the `frame32.gif` for the task bar icon and `frame.gif` for the application icon. Have a look at my terrible drawing I used to confirm this by editing each of the frame gifs. I suspect that on your setup you might be using one of the png files because I don't see the white background. This is something else I need to look into.

image

You are right in that the icon is not clear to see as an application icon so I'll try to work with the designer to see what can be done. I won't rule out me doing something dumb either.

**Comment by arcturus2** [comment]
> because I don't see the white background. This is something else I need to look into.

Never mind. It turns out that the white background appeared because I saved my debug version of those frame image files in paint.

**Comment by cygnus-x-1** [comment]
> You are right in that the icon is not clear to see as an application icon so I'll try to work with the designer to see what can be done. I won't rule out me doing something dumb either.

Perhaps it just needs some anti-aliasing applied.

**Comment by cygnus-x-1** [comment]
Another thing I noticed - the 'Constellation' options uses the old icon (it can be found in the Core Preferences module).

**Comment by arcturus2** [comment]
For those interested, I'm trying to get some help from the original designer to see if the quality of the gif can be improved.

**Comment by arcturus2** [comment]
This is what it looks like now. I've noticed that the taskbar icon has a white background so need to get that fixed 🤦‍♂ 

image

WIP...

**Comment by arcturus2** [comment]
image

This is what it looks like now after fixing the transparency issue. Perhaps we can continue improving this later. I am keen to get this change in given the time and $$$ spent on this.

Any further comments?

**Comment by cygnus-x-1** [comment]
> Any further comments?

This looks much better than before.

**Pull request merged**
