### PR TITLE
Unit test guidelines

### PR DESCRIPTION
**Pull request by antares1470**
### Description of the Change

Added some unit testing guidelines. I don't by any means claim to be an expert on writing unit tests but this what I've learned to be helpful when writing unit tests for Constellation. 

### Why Should This Be In Core?

It's helpful to have a standard to follow for unit tests which in turn helps improve consistency across unit tests.

### Benefits

It's helpful to have a standard to follow for unit tests which in turn helps improve consistency across unit tests.

### Possible Drawbacks

If not maintained, these could get out-of-date

### CODE REVIEW

**Review by Delphinus8821 — APPROVED** [review]

**Comment by aldebaran30701** [comment]
Is it worth mentioning to use NGTest, and Mockito as the standard for testing?
Other than the above suggestion, it reads well and gets the point across

**Comment by antares1470** [comment]
> 
> 
> Is it worth mentioning to use NGTest, and Mockito as the standard for testing?
> Other than the above suggestion, it reads well and gets the point across

Good pickup. I'll add that now

**Review by aldebaran30701 — APPROVED** [review]

**Review by Delphinus8821 — APPROVED** [review]

**Review by Auriga2 — APPROVED** [review]

**Comment by arcturus2** [comment]
Awesome @antares1470.

I'm wondering if we can add something about using a StoreGraph instead of DualGraph's. Something like:

When you need to test with a graph, create a `StoreGraph` so that you can focus on the test and not have to deal with read/write locks. Testing of read/write locks is already covered elsewhere.

Also can we have one that talks about using the minimum amount of attributes to cover the test? Something like:

Create the minimum amount of attributes to satisfy your unit test. This helps explain exactly the minimum requirements the plugin needs to function. Also avoid creating unnecessary amount vertices and transactions. In some cases 3 vertices is sufficient to create the context for your test.

@antares1470 I'd also like to tap into unit vs integration but until we have a proper naming convention for it we can omit this for now.

**Comment by antares1470** [comment]
> 
> 
> Awesome @antares1470.
> 
> I'm wondering if we can add something about using a StoreGraph instead of DualGraph's. Something like:
> 
> When you need to test with a graph, create a `StoreGraph` so that you can focus on the test and not have to deal with read/write locks. Testing of read/write locks is already covered elsewhere.
> 
> Also can we have one that talks about using the minimum amount of attributes to cover the test? Something like:
> 
> Create the minimum amount of attributes to satisfy your unit test. This helps explain exactly the minimum requirements the plugin needs to function. Also avoid creating unnecessary amount vertices and transactions. In some cases 3 vertices is sufficient to create the context for your test.
> 
> @antares1470 I'd also like to tap into unit vs integration but until we have a proper naming convention for it we can omit this for now.

Thanks @arcturus2. I'll add something about using StoreGraph.

Regarding your other suggestion, I already kind of cover this when explaining what a non-empty graph should compose of but maybe I can make some of your points more explicit

**Review by GammaVel — APPROVED** [review]
Looks great to me!  Thanks for putting these together. A couple of things - just wondering if you wanted to mention that it is good practice to make the unit test fail to see the test is working correctly. And each new part of code it is expected to have unit tests associated with it as part of Test Driven Development?

**Review by sol695510 — APPROVED** [review]

**Review by arcturus2 — APPROVED** [review]
amazing stuff thank you @antares1470

**Pull request merged**
