### PR TITLE
Avoid view updates when hidden

### PR DESCRIPTION
**Pull request by aldebaran30701**
### Description of the Change
This is a feeler PR for the way it is implemented and if approved, will allow me to extend it to any view requiring an update. 
Please pay attention to the section where booleans are set as I am not 100% sure on what sequence of events will need to occur when a view is hidden but floating?

The view framework now has an easily accessible boolean flag for testing if it isvisible or not.

**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~**

**EDIT:**
Implemented in all views except the following few below:

- Find view - Not currently on Generic TopComponent Framework
- Histogram - Not currently on Generic TopComponent Framework
- Timeline - Not currently on Generic TopComponent Framework
- NamedSelection - Utilises an odd listening framework for graph listening and could not implement without bugs
- Quality Control - Once DAV is opened, QCV launches an instance and ALWAYS refreshes on graph changes.

I worked on getting QCV avoiding updates when none of (QCV or DAV) were opened, but struggled with cyclic dependencies. I pose this as a question to wether this should be something tackled in another issue, or if the default behaviour is acceptable.

The others will need to be switched over to the generic framework as in #332 

### Alternate Designs
None realised

### Why Should This Be In Core?
Performance improvements

### Benefits
Performance improvements

### Possible Drawbacks
none realised

### Verification Process
Testing of update within Table view when it is visible or not.

### Applicable Issues
#32

### CODE REVIEW

**Comment by arcturus2** [comment]
I will have a closer look at this @aldebaran30701. It was good you put this in the `AbstractTopComponent`.

**Comment by arcturus2** [comment]
@aldebaran30701 Travis is failing here too. Can you please marge changes from master?

**Comment by aldebaran30701** [comment]
I've implemented most of the views to not listen when minimized, and tested switching graphs as well as reloading the view to ensure with the correct graph's state.

**Comment by arcturus2** [comment]
@aldebaran30701 I was doing testing on the Table View and noticed that it was still updating when I put some break points in. I'll let you know what I find.

**Comment by aldebaran30701** [comment]
Hi @arcturus2 It appeared that I assumed I had implemented the table view, and skipped looking through all cases when I went to fully implement this.
I've added the case now and it should be ready for review. 👍

**Comment by arcturus2** [comment]
>    Quality Control - Once DAV is opened, QCV launches an instance and ALWAYS refreshes on graph changes.
I worked on getting QCV avoiding updates when none of (QCV or DAV) were opened...I pose this as a question to wether this should be something tackled in another issue, or if the default behaviour is acceptable.

I've had a think about this and for now lets deal with this one later @aldebaran30701.

Also, I've also done a lot of testing and this PR will help a lot with less CPU cycles! I've made some suggestions to this PR and created PR #626 with suggestions. Note that there is way more files in my PR which has changed but that was due to me having to merge in `master`. If you merge `master` into this PR then you will be able to see the actual suggestions I'm proposing.

**Pull request merged**
