### PR TITLE
Plugin Parameter ux improvements

### PR DESCRIPTION
**Pull request by antares1470**
### Prerequisites

- [x] Reviewed the [checklist](CHECKLIST.md)

- [x] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

Have made a number of UX improvements, mostly for plugin parameters:
- added some default values to required parameters where appropriate
- marked required parameters as required (*), making it clear in the interface when parameters are required
- GUI for String, File, Single Choice, and Multi Choice parameters now goes red if you input a blank answer into a required parameter
- replaced remaining stack trace prints with log entries

### Alternate Designs

Considered adding a key to top of the parameter pane (to indicate what * meant) but decided it should hopefully be clear enough without (due it being commonly used for the same thing in other applications and forms)

### Why Should This Be In Core?

Improves user experience around plugins. Changes made to parts of Core which will benefit any created modules on top of Core.

### Benefits

Improved user experience

### Applicable Issues

#48

uxParameterImprovementsDemo

### CODE REVIEW

**Comment by mimosa2** [comment]
In Analytic view when deselecting transaction type(Unknown) changes the color red as expected. When moving to other analytics and back the previous one doesn't keep the color change.

**Comment by antares1470** [comment]
> In Analytic view when deselecting transaction type(Unknown) changes the color red as expected. When moving to other analytics and back the previous one doesn't keep the color change.

I wonder if this is caused by the analytic view possibly creating a new pane each time you select a different analytic? The catch with my implementation is that required parameters only go red when the value has been changed to something invalid (normally blank). I intentionally did it this way so that the parameter doesn't show red before you have the chance to edit it. This means though that a parameter will never display in the pane as red by default, regardless of whether or not the value contained in the parameter is actually valid.

I think the only way this could effectively be resolved then would be for me to change the logic slightly and allow a field to be red by default if need be. The catch with this though is that it will be blank required fields will all be red, regardless of whether you've actually touched them (or intend to touch them). Personally I prefer what I've done already, but I'm biased to my own thoughts so interested to hear what other people think

**Comment by aldebaran30701** [comment]
If you think about it, the * will tell the user that it is required, and if they miss that it will error or prompt for completion of that field. I don't see a way around apart from validating on creation of the input. Which as you said will just display as red boxes all the time

**Review by aldebaran30701 — APPROVED** [review]

**Review by arcturus2 — APPROVED** [review]
Nice work @antares1470 and apologies it took so long to review this one.

**Review by mimosa2 — APPROVED** [review]

**Pull request merged**
