### PR TITLE
Analytic view NPE on behalf of @formalhaut69

### PR DESCRIPTION
**Pull request by aldebaran30701**
### Description of the Change
move currentquestion outside of the JFX platform thread

#648 had some build file issues so another PR was made.

If you'd like to test this, I was able to reproduce this issue frequently when performing the reproducer steps in this issue; #629

### CODE REVIEW

**Comment by arcturus2** [comment]
@formalhaut69 please see my comment above.

**Comment by formalhaut69** [comment]
> @formalhaut69 please see my comment above.

@arcturus2, I haven't seen this NPE before, I hope my change didn't produce this. I'll take a look

**Comment by Auriga2** [comment]
I tried in master but couldn't recreate any exception, following the steps in #629.

**Comment by aldebaran30701** [comment]
@arcturus2 @formalhaut69 Would you like me to close this PR and leave the corresponding ticket open for another implementation? The ticket is #628

**Comment by arcturus2** [comment]
Yes please @aldebaran30701 as based on testing I think it needs a re-think

**Pull request closed without merging**
