### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by arcturus2**
### Description of the Change

* Update with steps on how to build a standalone version
* Improve formatting
* Remove reference to not supporting MacOSX (because now we do!)

### CODE REVIEW

**Comment by Auriga2** [comment]
Tried the below from constellation-app/constellation  (constellation-app/constellation-applications works)
> Right click on `Build Script` and run the `build-zip`
> * Navigate to the `dist` folder to get `constellation.zip` file

But still get the error when running the exe
image

If I click yes:
image

Should I follow this here? 
>* If you want to use a specific JRE then copy this to the same level as the `bin` folder and call it `jre`.

**Comment by arcturus2** [comment]
@Auriga2 

If you try to run the .exe it will try to look for the local `'jre' folder but if it can't find it then it will look at the system wide version of Java. This is expected.


> Should I follow this here?
> If you want to use a specific JRE then copy this to the same level as the bin folder and call it jre.

Yep, follow this and you should be good to go.

**Comment by Auriga2** [comment]
Had trouble figuring out how to find what to copy as 'jre'. I figured it out by comparing the folder content with the working one!
I guess specifying `zulu11.37.19-ca-fx-jdk11.0.6-win_x64 folder ` at least as an example, would help someone.

**Comment by arcturus2** [comment]
Updated @Auriga2, thank you for the feedback.

**Pull request merged**
