### PR TITLE
updated whatsnew layout

### PR DESCRIPTION
**Pull request by antares1470**
### Description of the Change

As per @GammaVel's suggestion, I've updated the Whats New Page layouy by centering the text and adding some padding to the sides

WhatsNewLayout

### Why Should This Be In Core?

Better layout

### Benefits

Better layout

### Applicable Issues

#1083

### CODE REVIEW

**Comment by arcturus2** [comment]
@antares1470 how about this ?

image

So we are just centering the content with more padding. Here are my changes going off `master`. There is an extra redundant call to the `paddingProperty` which I've removed too so wanted to show the diff.

```diff
diff --git a/CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/WhatsNewViewPane.java b/CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/WhatsNewViewPane.java
index 19059eb26..b856bc1bb 100644
--- a/CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/WhatsNewViewPane.java
+++ b/CoreWhatsNewView/src/au/gov/asd/tac/constellation/views/whatsnew/WhatsNewViewPane.java
@@ -87,14 +87,13 @@ public class WhatsNewViewPane extends BorderPane {
 
             final VBox contentVBox = new VBox();
             whatsNewViewPane.setCenter(contentVBox);
-            contentVBox.paddingProperty().set(new Insets(5, 5, 5, 5));
 
             // Create a checkbox to change users preference regarding showing the Whats New Page on startup
             final Preferences prefs = NbPreferences.forModule(ApplicationPreferenceKeys.class);
             final CheckBox showOnStartUpCheckBox = new CheckBox("Show on Startup");
             contentVBox.getChildren().add(showOnStartUpCheckBox);
             contentVBox.setAlignment(Pos.TOP_RIGHT);
-            contentVBox.paddingProperty().set(new Insets(5, 5, 5, 5));
+            contentVBox.paddingProperty().set(new Insets(5, 150, 5, 150));
             showOnStartUpCheckBox.selectedProperty().addListener((ov, oldVal, newVal)
                     -> prefs.putBoolean(ApplicationPreferenceKeys.TUTORIAL_ON_STARTUP, newVal));
             showOnStartUpCheckBox.setSelected(prefs.getBoolean(ApplicationPreferenceKeys.TUTORIAL_ON_STARTUP, ApplicationPreferenceKeys.TUTORIAL_ON_STARTUP_DEFAULT));
```

**Comment by antares1470** [comment]
@arcturus2 that looks at lot nicer

**Comment by arcturus2** [comment]
> @arcturus2 that looks at lot nicer, I'll make the changes unless you would prefer to just submit a PR yourself?

Nah u go for it @antares1470

**Comment by antares1470** [comment]
Changes have been pushed @arcturus2

**Review by arcturus2 — APPROVED** [review]

**Pull request merged**
