### PR TITLE
Improve overall performance for renderTextAsLigatures

### PR DESCRIPTION
**Pull request by arcturus2**
### Description of the Change

With a traditional Map as a cache, the performance of renderTextAsLigatures has improved greatly and the slowest part next was adding the glyphs to the buffer. This part was synchronized due to threading so removing the synchronized calls and therefore threading improves the performance further. As a result all the recent threading added by @Nova-2119 was needed to be removed. Tried adding Guava caching with a purge timeout but it was the slowest part and negated the performance improvements being made.

With caching we are having subsequent graph opens and graph changes like deletes etc working much faster.

The following is an overall performance comparing v1.2 with `master` and this branch. This is testing on a 30k node and transaction graph.

The performance improvements was gained by caching the bulk of the work done by `renderTextAsLigatures` and removing calls to `synchronize` which and therefore required all the threading to be removed. As a result the memory spikes are a lot less meaning GC work is less intense and the CPU spikes are less too.

image

**Important Note - Note that it looks like it is taking 73 seconds to open in current `master`. This is misleading and inaccurate and apologies in advance. Remember that `master` is the only threaded version so this is the total CPU time for all threads. In practice it took around 35 seconds to render.**

As you can see though the performance is not as fast as the original v1.2, it is significantly faster than v2. Note that with caching, deleting nodes etc is faster than the original v1.2 by 100ms so interacting with the graph should be better now.

v1.2 opening graph 1st time:
v1 2 30k nodes and links 1st open

v1.2 opening graph 2nd time:
v1 2 30k nodes and links 2nd open

v1.2 deleting half of the graph:
v1 2 30k nodes and links delete half

master opening graph 1st time:
master 30k nodes and links 1st open

master opening graph 2nd time:
master 30k nodes and links 2nd open

master deleting half of the graph:
master 30k nodes and links delete half

latest opening graph 1st time:
latest 30k nodes and links 1st open

latest opening graph 2nd time:
latest 30k nodes and links 2nd open

latest deleting half of the graph:
latest 30k nodes and links delete half

**Memory and Threads Performance Usage**

This is current `master` opening the 30k nodes and links and then deleting half the graph:

master 30k nodes open and delete

This is the current branch doing the same thing. You will notice the memory usage is low again and threads are less. We knew that adding threads was going to increase memory usage but practically this is causing problems with GC called a lot more and peaking memory usage, causing an out of memory to occur sometimes.

latest 30k nodes open and delete

### Alternate Designs

I looked at using Guava caching to purge items in the cache that was written x minutes ago but it was slowing things down greatly compared to using a simple Map and the performance gains was less. Changing the cache to clear after x hours didn't make a difference either.

### Benefits

There is a reduction in cpu and memory spikes and this means the GC works a bit less. Subsequent graph opens are so much quicker now thanks to caching.

### Possible Drawbacks

The caching won't purge anything so over time the memory use will increase but I feel this is a worthwhile trade off with the current version as the memory retained does greatly help with graph interaction which is what you do most once your in Constellation.

### Verification Process

Compared v1.2, `master` and this branch running if profiling. In v1.2 I profiled `au.gov.asd.tac.constellation.visual.opengl.utilities.GlyphManager.renderTextAsLigatures`. In `master` I profiled `au.gov.asd.tac.constellation.visual.opengl.utilities.glyphs.GlyphManagerBI.renderTextAsLigatures`. In this branch I also profiled `au.gov.asd.tac.constellation.visual.opengl.utilities.glyphs.GlyphManagerBI.buildLigature`

### Applicable Issues

#984 and #980

### CODE REVIEW

**Review by antares1470 — APPROVED** [review]

**Comment by arcturus2** [comment]
@antares1470 noting that you approved this I wanted to make the following statement clear as not to mislead the perfomance results. I have updated the description witrh the following...

**Important Note - Note that it looks like it is taking 73 seconds to open in current `master`. This is misleading and inaccurate and apologies in advance. Remember that `master` is the only threaded version so this is the total CPU time for all threads. In practice it took around 35 seconds to render.**

**Review by aldebaran30701 — APPROVED** [review]
Been testing for a little while now, and it seems to be fine. no errors. For a second I thought i found an issue but it was a 160k sphere graph and it just took longer than usual to load. Still a seemingly faster load than current master.

**Comment by arcturus2** [comment]
> Been testing for a little while now, and it seems to be fine. no errors. For a second I thought i found an issue but it was a 160k sphere graph and it just took longer than usual to load. Still a seemingly faster load than current master.

Cool. Deleting parts of the graph should be quicker than master as well. Also it should be using a lot less memory overall. Closing and opening that graph should be a fraction of current master.

**Comment by ben-manes** [comment]
FYI: Guava defaults to a conservative setting (4) and the concurrencyLevel has to be increased in performance sensitive code (e.g. 64). Caffeine cache, a rewrite of Guava’s, is much faster and dynamical tunes itself so no setting is needed.

**Comment by arcturus2** [comment]
> FYI: Guava defaults to a conservative setting (4) and the concurrencyLevel has to be increased in performance sensitive code (e.g. 64). Caffeine cache, a rewrite of Guava’s, is much faster and dynamical tunes itself so no setting is needed.

Thanks @ben-manes this looks promising. I profiled it and Caffeine isn't even making it on the profile stack. It all seems to work really fast, just like a Map would. I'll do a bit more testing but I think I will go ahead with including Caffeine as the cache.

**Pull request merged**
