### PR TITLE
Improve the split logic in the Split Nodes plugin

### PR DESCRIPTION
**Pull request by Auriga2**
### Description of the Change
Current split logic is inconsistent, for instance, when the Split Characters present consecutively in the middle or at the beginning, it duplicates the selected node in addition to the other new nodes splitted from the rest of the identifier. If the Split Characters present consecutively in the end, it just split the rest of the identifier.

### Alternate Designs
N/A

### Why Should This Be In Core?
Better UX

### Benefits
Better UX

### Possible Drawbacks
N/A

### Verification Process
This is the proposed criteria:

Split on first occurrence: (ALL_OCCURRENCES = False)
,,, split by , => create one node with ,,
vvv split by v = create one node with vv
v,,v split by , = create 2 nodes (v and ,v) as between ,, is no identifier
,,v split by , = create 1 node (,v) as nothing between the first two ,,s
v,, split by , = create 2 nodes (v and ,)

Split on all occurrences:: (ALL_OCCURRENCES = True)
,,, split by , = not create anything because of nothing between delimiters.
vvv split by v = the same as above.
v,,v split by , = create 2 nodes (v and v) as between ,, is no identifier
,,v split by , = create 1 node (v) as nothing between the first two ,,s
v,, split by , = create 1 node (v)

### Applicable Issues
#822

### CODE REVIEW

**Review by antares1470 — APPROVED** [review]

**Comment by mimosa2** [comment]
@Auriga2 I have tested this one and looks good. The split identifier logic works as per the proposed criteria. 
Only one thing I noticed was the Raw attribute also get splitted which doesn't happen in the current application. I am not sure if this is an expected change.

**Comment by Auriga2** [comment]
@mimosa2 From what I can see, the `Raw` and even the `Label` field changes when  we change the Identifier, similar to V2.0.0
Great if you can attach a screen capture if they do not behave the same way for you.
image

**Comment by mimosa2** [comment]
Ok. Thanks @Auriga2. I will check this out again.

**Review by arcturus2 — CHANGES_REQUESTED** [review]
@Auriga2 it looks like the build failed because the test `testQueryWithNoResultingNodesToSplitTo_AllOccurancesNotSelected_WithoutDuplicateTransactions` failed. Please check when you can.

**Comment by mimosa2** [comment]
@Auriga2, you are right, the Constellation - v2..0.0 version behaves the same way as you mentioned. Sorry I must have tested a different version on our side.

**Comment by Auriga2** [comment]
> @Auriga2 it looks like the build failed because the test `testQueryWithNoResultingNodesToSplitTo_AllOccurancesNotSelected_WithoutDuplicateTransactions` failed. Please check when you can.

Fixed

**Comment by arcturus2** [comment]
Awesome work on the unit testing @Auriga2, loving it!

**Review by arcturus2 — APPROVED** [review]

**Pull request merged**
