### PR TITLE
fixed some potential issues around data access category ordering

### PR DESCRIPTION
**Pull request by antares1470**
### Prerequisites

- [x] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

Add some fixes to potential issues that could arise in extending Constellation.

For instance, it appeared the code was assuming that any categories being looked at were one word with no spaces so a category such as 'My New Category' could disappear after ordering as it would be looking for 'My' rather than 'My New Category'. Also appeared the ordering was no longer looking at the category position for default ordering so this has been fixed.

### Why Should This Be In Core?

Code in Core still needs to account for extending the application beyond Core.

### Benefits

Fixes potential issues with data access category ordering

### Possible Drawbacks

Nil

### Applicable Issues

#1682

### CODE REVIEW

**Comment by OrionsGuardian** [comment]
There is an issue when you first run Constellation from a clean build:
image

If you have not opened the Data Access View, and there is no currently saved properties file for the Data Access View settings, then the Options screen will be blank.

**Comment by antares1470** [comment]
> There is an issue when you first run Constellation-Adaptors from a clean build: image
> 
> If you have not opened the Data Access View, and there is no currently saved properties file for the Data Access View settings, then the Options screen will be blank.

I can confirm this. I also got this doing the same for core only so that suggests to me that there is something wrong with the way it is finding the categories

**Comment by antares1470** [comment]
@OrionsGuardian I've resolved this by generating the list if DAV hasn't been opened (and no order preferences exist). The issue was that the function in `LookupPluginsTask` was only being called from the `DataAccessPaneState` (i.e. wasn't going to be called before Data Access View was opened).

The catch with this change is that it does make opening the panel take a little longer if it has to generate the list but I couldn't find any way around it (you can quickly get all possible categories, but ultimately you need to look at all data access plugins to determine which ones are and aren't being used). This timing issue isn't a problem once Data Access View has been opened or the preferences exist.

**Comment by OrionsGuardian** [comment]
> @OrionsGuardian I've resolved this by generating the list if DAV hasn't been opened (and no order preferences exist). The issue was that the function in `LookupPluginsTask` was only being called from the `DataAccessPaneState` (i.e. wasn't going to be called before Data Access View was opened).
> 
> The catch with this change is that it does make opening the panel take a little longer if it has to generate the list but I couldn't find any way around it (you can quickly get all possible categories, but ultimately you need to look at all data access plugins to determine which ones are and aren't being used). This timing issue isn't a problem once Data Access View has been opened or the preferences exist.

This seems fine to me. It's not a frequently used screen.
There's only a very small delay in loading the screen for the first time, which I would consider to be acceptable.

**Review by OrionsGuardian — APPROVED** [review]

**Review by Delphinus8821 — APPROVED** [review]

**Pull request merged**
