### PR TITLE
Delimited File Importer - Option to insert column headers

### PR DESCRIPTION
**Pull request by Auriga2**
### Description of the Change
An option `Insert Column Headers` is added in the Delimited File Importer source pane. When importing from delimited files that don't contain column headings, the option can be enabled to insert column headers as `Col1`, `Col2`, `Col3` etc.

### Alternate Designs
n/a

### Why Should This Be In Core?
Better UX, as without this, the first row will be skipped as the column headers.

### Benefits
It can now import from files with no column headers.

### Possible Drawbacks
n/a

### Verification Process

1. Create a CSV file that doesn't contain headers, e.g.:
5,6,7,2009-12-05 23:59:59,2009-12-1
1,1,1,2009-12-15 23:59:59,2009-12-12
a,a,a,2009-12-25 23:59:59,2009-12-31

2. Enable the check box and import it.
3. Confirm the columns are inserted and the first row of real data is not lost.

### Applicable Issues
https://github.com/constellation-app/constellation/issues/573

### CODE REVIEW

**Review by antares1470 — CHANGES_REQUESTED** [review]
Did some testing of this and made some observations:
- I noted that you had to check the column headers checkbox before you added the file. I think it would be good if possible to be able to do this in either order (and the UI reflect accordingly)
- Related to above point but it appears the tickbox is applied when I add a file and that is then applied to all the files that are currently added. In other words, if I add a file with column headers checked and then add another file with column headers unchecked, the result shows both files without column headers added (including the one I added with column headers checked). It's possible though this issue is related to the greater problem of how importing multiple files is currently handled.

**Comment by Auriga2** [comment]
This sounds good as it will reduce one click in the workflow. But it will also double the options in the File Parser drop down (to 12), and this option would be used only in rare cases I presume. (In terms of coding, it also requires a new set of ImportFileParser classes (6 new) added.)
image


So I still prefer to move the section up, or at least move the new option into the Options list at top left corner? The former will also fulfill the UX Design Review suggestion below, and is a simple fix:
> 3.Based on previous point, consider swapping ‘Destination’ and ‘Files’ sections to swap position under ‘Source’ categories

image

**Comment by antares1470** [comment]
> We can also rename the checkbox to something like "First row of the file is header row" and keep it checked by default?

@Auriga2 that should be fine. To avoid the text being too large though, instead of "First row of the file is header row" maybe something like "File(s) has headers".

Side note: With your proposed solution, the Destination drop-down sits right below the Source pane title which looks a little funny. In terms of flow, I think it makes more sense to pick your destination after you load the file rather than before. Maybe you can keep the other options above the Files part and move the Destination drop-down to below the files part(?)

**Comment by cygnus-x-1** [comment]
This is looking good from the screenshots. I'd suggest renaming "Import File Parser" to simply "File Parser", and "Insert Column Headers" to "Include Headers" (on by default, which would assume the file has headers). I'm going to check out the branch and do a bit of testing... I'll let you know if I find anything.

**Comment by cygnus-x-1** [comment]
Some feedback from testing:

- You should be able to toggle headers on and off after the file has been loaded into the preview pane. As it is now, I needed to remove all files, then toggle the headers option, then add the files back to see the change.
- I think I like your suggestion about moving the "Source" options bar to the top as it better matches the workflow; you're forced to focus on what graph you're populating up front and what file type you're importing... particularly important as you can't change that after adding files.

And some broader feedback about the Delimited File Importer...
- The "Tab Separated" file parser should probably be called "TSV".
- The "SQLite" file parser is somewhat redundant now that the JDBC Importer exists.
- I'd suggest renaming "Import from Delimited File" to simply "Import from File" as the less technical terminology is more approachable. Similarly, rename "Import from JDBC" to "Import from Database".

**Comment by arcturus2** [comment]
@Auriga2 I gave the PR a test and the newer UI in the screenshots look better and the feedback from others is also positive. So keen to test the PR again based on the changes you decide to make.

The additional suggestions from @cygnus-x-1 are great but if you are not able to do them in this PR then happy for that to be done separately later on if it could be documented by either @cygnus-x-1 or yourself. If you have time to do it all in this PR then also great and fine - will leave that up to you.

**Comment by Auriga2** [comment]
Yeah good feedback. Thanks everyone.  I'll try to fix everything here.

**Comment by Auriga2** [comment]
"File(s) Has Headers" or "Include Headers"? A combined "Files Include Headers" sounds better IMO. 

With regards to moving the Destination graph selection, the comments above are contradictory. In fact, in the current version, "Destination" sits in the Source pane. Moving it beloa the Files section wll do the same. Ideally we should move it to a new Pane. Or as a simple fix, can we keep it at the top and rename "Source" to "Source and Destination" or "Import Details" or ""Details" or something similar?

Shall we remove "SQLite" file parser?

**Comment by arcturus2** [comment]
@Auriga2 I don't mind the quick fix of renaming the section to "Source and Destination". Ideally it would be its own section but not essential.

>Shall we remove "SQLite" file parser?
OK.

**Review by antares1470 — CHANGES_REQUESTED** [review]
Minor thing but the panes themselves are still titled "From Delimited File..." and "From JDBC..." despite the name changes occurring elsewhere so it would be good to fix that.

**Comment by Auriga2** [comment]
@antares1470 I cannot find where to fix this, it doesn't pop up with a string search.

**Comment by antares1470** [comment]
> 
> @antares1470 I cannot find where to fix this, it doesn't pop up with a string search.

So it turns out I missed something when I built the branch. After doing so, the tab names presented as expected

**Review by antares1470 — APPROVED** [review]

**Review by arcturus2 — APPROVED** [review]

**Comment by GammaVel** [comment]
hi @Auriga2, is this the issue which you are using to remove the colon after the E.g  ? If so, I have noticed this Text is also in this hints section too. It would be good to update both at the same time. 


image

**Comment by Auriga2** [comment]
Yes, I have fixed all occurrences, looks like you don't have these changes yet.

**Pull request merged**
