### PR TITLE
module-dependencies-refactor

### PR DESCRIPTION
**Pull request by cygnus-x-1**
### Description of the Change

After starting work on https://github.com/constellation-app/constellation/issues/42, I quickly re-discovered the issue of Constellation's modules not being arranged in a very modular way. It was very easy to introduce cyclic dependencies, and removing any modules below the views tends to wipe out the entire application. I've refactored a lot of code in order to make Constellation's module hierarchy simpler, and to remove a lot of these issues. I've also addressed all the goals of issue #42.

### Alternate Designs

There are likely many ways to arrange the module hierarchy, but I've done my best to keep it simple.

### Why Should This Be In Core?

This is a sorely needed refactor years in the making.

### Benefits

This change makes Constellation's modules largely linearly dependant, meaning you can turn any of them off and still have a working application. This should also make it easier to add new features into the lower level modules in the future.

### Possible Drawbacks

As mentioned, a lot of code have moved around. There could easily be issues I missed during my testing, and there is likely to be breaking changes in terms of backwards compatibility.

### Verification Process

I manually executed every high-level feature of Constellation to ensure correct behaviour.

### Applicable Issues

None, that i'm aware of...

### CODE REVIEW

**Comment by cygnus-x-1** [comment]
@arcturus2 - this is not entirely done yet, but its getting close. I've submitted this pull request now so you can start to take a look at it and highlight any major issues.

**Comment by arcturus2** [comment]
Thank you for this @cygnus-x-1. The clean up work you've done is really impressive. :+1: 

Would you be able to update CHANGELOG.md recording the modules that got moved/added/deleted please as that will help understand this PR.

**Comment by cygnus-x-1** [comment]
@arcturus2 - I think the refactoring is all done now, please take a look. I'll still need to move it over to the nb11 branch before you merge it - what's the name of the branch I should use?

**Comment by cygnus-x-1** [comment]
There is an error I keep seeing on opening the SimpleGraphTopComponent.

java.lang.ClassNotFoundException: au.gov.asd.tac.constellation.functionality.visual.SimpleGraphTopComponent

The TopComponent opens just fine after that and there seem to be no issues. I can't find any reference to that class reference or any part of it anywhere in the code base. Was this an existing issue?

**Comment by arcturus2** [comment]
Closing this given the focus is on #291

**Comment by cygnus-x-1** [comment]
> Closing this given the focus is on #291

Keep in mind that merging this into master will make merging master into https://github.com/constellation-app/constellation/pull/291 much easier.

**Pull request merged**
