### PR TITLE
Analytic View Reset Bug

### PR DESCRIPTION
**Pull request by Delphinus8821**
### Prerequisites

- [x] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change
Ensures that any changes made by the analytic view are always reset when the view is closed or a new analytic is run.

### Why Should This Be In Core?
Bugfix

### Verification Process
Open multiple graphs
Run an analytic on each and select some of the graph visualisations (color, hide and size)
Close the analytic view
Check that the changes made by those graph visualisations have been reverted on all graphs.

### CODE REVIEW

**Review by OrionsGuardian — APPROVED** [review]

**Review by antares1470 — CHANGES_REQUESTED** [review]
Was testing with a few graphs open, ran analytic on the first graph fine but when I switched graphs I got the following exception:
```
java.lang.NullPointerException

au.gov.asd.tac.constellation.views.analyticview.translators.AnyToReportTranslator.buildVisualisation(AnyToReportTranslator.java:47)
au.gov.asd.tac.constellation.views.analyticview.translators.AnyToReportTranslator.buildVisualisation(AnyToReportTranslator.java:29)
au.gov.asd.tac.constellation.views.analyticview.AnalyticResultsPane.lambda$displayResults$2(AnalyticResultsPane.java:117)
java.base/java.util.HashMap$Values.forEach(HashMap.java:976)
java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
au.gov.asd.tac.constellation.views.analyticview.AnalyticResultsPane.lambda$displayResults$4(AnalyticResultsPane.java:113)
```

**Comment by Delphinus8821** [comment]
> Was testing with a few graphs open, ran analytic on the first graph fine but when I switched graphs I got the following exception:
> 
> ```
> java.lang.NullPointerException
> 
> au.gov.asd.tac.constellation.views.analyticview.translators.AnyToReportTranslator.buildVisualisation(AnyToReportTranslator.java:47)
> au.gov.asd.tac.constellation.views.analyticview.translators.AnyToReportTranslator.buildVisualisation(AnyToReportTranslator.java:29)
> au.gov.asd.tac.constellation.views.analyticview.AnalyticResultsPane.lambda$displayResults$2(AnalyticResultsPane.java:117)
> java.base/java.util.HashMap$Values.forEach(HashMap.java:976)
> java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
> au.gov.asd.tac.constellation.views.analyticview.AnalyticResultsPane.lambda$displayResults$4(AnalyticResultsPane.java:113)
> ```

I cannot reproduce this.

**Comment by antares1470** [comment]
> I cannot reproduce this.

I've apparently been able to reproduce this quite consistently. Here is a gif demonstrating it:
analyticViewNullPointer

**Comment by antares1470** [comment]
I just gave it a test in v2.11-rc1 and got it there as well. Not exactly sure why you can't reproduce it given it seems I can do so rather consistently (maybe its an environment thing?). Regardless, it seems it isn't an issue with this branch specifically

**Review by antares1470 — APPROVED** [review]

**Pull request merged**
