### PR TITLE
javahelp-update

### PR DESCRIPTION
**Pull request by cygnus-x-1**
# Description of the Change

The javahelp netbeans module and jhall jars are no longer downloaded from the thrid-party-jars repository in the ant build script, instead the javahelp (updated jhall) jar is retrieved as a regular maven dependency, and the updated javahelp netbeans module included with the Netbeans 11.3 distribution should be used.

Dependency versions have been been updated to latest.

A temporary scaling fix has been put in place to resolve the JOGL 2.4.0 HIDPI scaling issues (this should be removed when JOGL 2.4.0 is released on maven as it will have an internal fix for this).

Minor improvements to recent changes to the Table View, Delimited File Importer and JsonIO.

### Verification Process

Tested JavaHelp changes using a fresh Netbeans installation and Ivy cache on two different systems.

Tested HIDPI fix by opening graphs on a HiDPI display (Surface Book 2).

Manual testing of Table View column filter and Delimited File Importer attribute filter.

### Applicable Issues

https://github.com/constellation-app/constellation/issues/15
https://github.com/constellation-app/constellation/issues/387
https://github.com/constellation-app/constellation/pull/398
https://github.com/constellation-app/constellation/pull/400
https://github.com/constellation-app/constellation/pull/397

### CODE REVIEW

**Comment by cygnus-x-1** [comment]
@canis-majoris-42 could you confirm this works on your HIDPI display?

**Comment by cygnus-x-1** [comment]
@arcturus2 could you confirm this is correctly building distributions?

**Comment by arcturus2** [comment]
> @arcturus2 could you confirm this is correctly building distributions?

@cygnus-x-1 can you change line 215 in `build.xml` to the folder `distribution`? Sorry I'm asking you to fix my bug. With that change it opens without an error. Thank you.

```java
            <zipfileset dir="${basedir}/distribution/" prefix="${app.name}/"/>
```

**Comment by arcturus2** [comment]
@cygnus-x-1 FYI so the Travis build is failing here because it has the work around in place with the replaced jars. That would need to be corrected which I am happy to do straight after this gets merged when we get to that point.

**Comment by arcturus2** [comment]
Also the README needs to be updated to remove those workaround steps and also possibly a note to devs that previously did the workaround to revert it!

**Comment by cygnus-x-1** [comment]
Okay I believe this is ready to be merged now @arcturus2.

**Comment by arcturus2** [comment]
@cygnus-x-1 I merged this PR before testing it on the Mac. The work around code block has made a difference but it hasn't fixed it.
* Nodes are now being created the camera if that makes sense and I have to zoom out to see them.
* Selection no longer works probably because it is also happening behind the camera
* The x,y,z graph legend on the top right corner also isn't visible.

I'll continue having a look at modifying that code block to see if I can make it work on the Mac.

**Pull request merged**
