### PR TITLE
Load batch plugin parameters bugfix

### PR DESCRIPTION
**Pull request by mimosa2**
### Description of the Change

 A bug has been fixed when loading data access view preferences for batch plugins in options ->load. 

### Why Should This Be In Core?

Core functionality

### Benefits

Parameters will be selected correctly on load preferences. 

### Possible Drawbacks

N/A
### Verification Process

    Open DA view , select a batch plugin which has multiple plugins and select parameters in all plugins.

    Open Options -> Save to a file

    Close and open DA view

    Open Options -> Load and select the file

### CODE REVIEW

**Review by antares1470 — APPROVED** [review]

**Comment by arcturus2** [comment]
@mimosa2 a major refactor has taken place in https://github.com/constellation-app/constellation/pull/1392 and I am wondering if you are OK if I was to merge that first and get you to update this PR from that one?

**Comment by mimosa2** [comment]
That's fine @arcturus2. I can push this change after you merge.

**Comment by arcturus2** [comment]
Thanks @mimosa2 for understanding. So #1392 has been merged so please review the merge conflict and send through an update when you can.

**Comment by mimosa2** [comment]
Ok. I will look at that merge conflict. Thanks.

**Comment by mimosa2** [comment]
Closing this PR and removing the branch. New branch & PR will be created for this bug fix.

**Pull request closed without merging**
