### PR TITLE
Changed two more files to use from texture2D to texture as there are trace errors in Mac

### PR DESCRIPTION
**Pull request by rsabhi**
### Description of the Change

Changed two more files to use from texture2D to texture as there are trace errors when running with the new proposed change suggested on PR#120. Tested in Mac OS Mojave

### CODE REVIEW

**Comment by arcturus2** [comment]
@GCHQDeveloper601 if at all possible I'd like to include you in the review of future Mac OS changes. Are you able to test this PR when you get a chance?

**Comment by rsabhi** [comment]
@arcturus2, this PR is similar to the PR #120 so I would recommend it to be merged. Please let me know for any concern. Thanks

**Comment by GCHQDeveloper601** [comment]
> @GCHQDeveloper601 if at all possible I'd like to include you in the review of future Mac OS changes. Are you able to test this PR when you get a chance?

I'll be happy to do testing of future changes, however my development environment is still getting approved so won't be able to test these changes for a couple of weeks yet.

**Comment by arcturus2** [comment]
> I'll be happy to do testing of future changes, however my development environment is still getting approved so won't be able to test these changes for a couple of weeks yet.

Much appreciated @GCHQDeveloper601. Happy to wait.

**Comment by arcturus2** [comment]
@GCHQDeveloper601 I'm going to merge this as I have not heard back from you in a little while and see how things go based on further testing. Thanks again.

**Pull request merged**
