### PR TITLE
Notes View Update Exception

### PR DESCRIPTION
**Pull request by antares1470**
### Prerequisites

- [x] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first.

### Description of the Change

An exception was being by the notes view when one of the graph builders was opened when the notes view was closed. This was due to the notes view trying to update the UI while it was closed. The cause was the lack of a check to make sure the notes view was actually open before trying to make the GUI changes.

### Why Should This Be In Core?

Bug fix

### Benefits

bug fix

### Verification Process

Followed reproducer from original ticket

### Applicable Issues

#1583

### CODE REVIEW

**Review by mimosa2 — APPROVED** [review]

**Comment by Auriga2** [comment]
I tested the `bugfix/notes-view-exception` branch and still get the same exception.

**Comment by aldebaran30701** [comment]
I also get an exception following the reproducer in the ticket.
`
java.lang.NullPointerException
	at au.gov.asd.tac.constellation.views.notes.NotesViewPane.createNote(NotesViewPane.java:619)
	at au.gov.asd.tac.constellation.views.notes.NotesViewPane.lambda$updateNotesUI$14(NotesViewPane.java:519)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at au.gov.asd.tac.constellation.views.notes.NotesViewPane.lambda$updateNotesUI$15(NotesViewPane.java:519)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
[catch] at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)
`

**Comment by antares1470** [comment]
I also managed to get the exception to trigger again although I could only get it to happen sometimes and the process to trigger also wasn't consistent. Doing some debugging though, I did find that there was one other place that was often triggering a UI update without actually checking whether the notes view was open so I've added a check there as well. I haven't been able to get the exception since in testing but given how inconsistent the exception occurred previously, I can't say for certain it is gone (but it does look promising).

@Auriga2 @aldebaran30701 are you able to give it another test with these new changes?

**Comment by Auriga2** [comment]
I get the same exception when `Auto Notes` filter is enabled in Notes view, and then try to run the sphere graph builder. Once I get it, it's thrown again if  `Auto Notes` is selected again after  deselecting it in the filter. 

So to recreate consistently->Open consty -> Open Notes view->Select `Auto Notes` filter -> open the sphere graph builder.

**Comment by antares1470** [comment]
Thanks @Auriga2, I'll keep digging then

**Comment by antares1470** [comment]
@Auriga2 I've pushed a change to fix the null pointer directly at the source. Are you able to give it another test please?

**Review by Auriga2 — APPROVED** [review]
No more exceptions! Looks good now.

**Pull request merged**
