### PR TITLE
Right click context menu hierarchy when already existing sub-menus are specified

### PR DESCRIPTION
**Pull request by Auriga2**
### Prerequisites

- [ ] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change
Right click context menu hierarchy was not displaying correctly when multiple sub-menus specified including already existing items, in the `getMenuPath` of a Context menu. 

### Alternate Designs
n/a

### Why Should This Be In Core?
Fix the Right click context menu

### Benefits
Bug fix

### Possible Drawbacks
n/a

### Verification Process

1. Open a new Graph
2. Add a node to the graph
3. Right-click on the Node
4. Hover over the Layers option
5. Sub-menu should contain `Add Selection to Layer` and `Remove Selection from Layer` instead of `Remove Selection from Layer` after another `Layers` Sub-menu

### Applicable Issues
https://github.com/constellation-app/constellation/issues/1750

### CODE REVIEW

**Review by antares1470 — COMMENTED** [review]
@Auriga2 looks like there may be a unit test failing? Looks good otherwise

**Comment by Auriga2** [comment]
@antares1470 Looks like these fail in the master branch as well. I'll have a look on Wednesday, but any tips to narrow down will be accepted :-)
image

**Comment by Auriga2** [comment]
@antares1470 So did it all pass in verbose mode?

**Comment by antares1470** [comment]
> @antares1470 So did it all pass in verbose mode?

It did...although verbose mode just changes the logging, not the way it runs the tests themselves. Maybe the unit tests weren't actually an issue

**Review by antares1470 — APPROVED** [review]

**Review by OrionsGuardian — APPROVED** [review]

**Pull request merged**
