### PR TITLE
Convert TravisCI to GitHub Actions

### PR DESCRIPTION
**Pull request by aldebaran30701**
### Description of the Change
This change switches from **TravisCI** to GitHub Actions. 
- Triggers when a commit or pull request is added.
- Runs two jobs (Run Tests | Sonar Scan)
- Run Tests does update dependencies clean build from the Docker image and then runs all unit tests.
- Sonar Scan does update dependencies clean build from the Docker image and then scans the codebase.

**Future work**
- Cache the downloaded dependencies within the Docker container. (tried using the cache action and mounting it to the correct folder on Docker but it seems to always cache nothing even though there is only one `.ivy2/cache` directory at `/root/`)
- Add an action to message Gitter (using a web hook).
- Add an action to package up the release on tagged versions.

**Issues with this implementation:**
- Does update dependencies clean build twice. This is because I could not find a way to run sonar scanner in the same Docker container.

**What is needed to implement this in core:**
- Ensure GitHub has a `SONAR_TOKEN` secret with the value shared by the secret in Sonarcloud. 
- The project key within `sonar-project.properties` must match the repository (does in this PR)
- The organization within `sonar-project.properties` must match the repository (does in this PR)
- There is a hardcoded string check for equality to 'constellation-app/constellation' within `sonar.sh` which must also match the repository (Does in this PR).

**To test this PR:**
- You may have to merge it in, and review subsequent PR and commits to master to test it is working.
- Open the actions menu at the top menubar for the Pull Request and review the logs/status marks.

### Applicable Issues
#929

### CODE REVIEW

**Comment by aldebaran30701** [comment]
@arcturus2 
https://github.com/constellation-app/constellation/runs/2136722944?check_suite_focus=true#step:4:9
This above line mentions that the env variable `SONAR_TOKEN` is not set. This leads me to believe the last step of the process is to create a github repository secret with the value of the secret stored within the repository settings for sonar cloud. This should allow the process to complete.

Before a full review is needed, I will migrate the sonar-scanner installation into the Docker image and get Gitter notifications working.

**Comment by aldebaran30701** [comment]
Setting up a webhook for Gitter.
Step 1: Gitter -> Room Settings -> Integrations -> add an integration: (GITHUB)
Step 2: Configure Manually -> Click done (Note the token)
Step 3: Github on this repo -> Settings -> Webhooks -> Add a webhook.
Step 4: Fill in settings as per image below. (Leave secret blank)
`https://webhooks.gitter.im/e/<gitter_token>`
image

This should conclude the setting of the gitter integration. No extraneous code necessary.

**Comment by aldebaran30701** [comment]
This PR is now ready to review! @arcturus2 just needs to add the sonar secret to github as described above, and it **should** pass all tests. (fingers crossed)

**Comment by arcturus2** [comment]
Its all working now @aldebaran30701 thank you very much!

**Review by arcturus2 — APPROVED** [review]
Thank you very much for doing this. It will be better for us to not fly blind again...this is really important to have back!

A few things:
* Regarding the future work is there a ticket to capture that? If not can you create one? Note that the Gitter integration is done so you can ommit that.
* A minor one but I will consider changing the `githubutilities` to another folder name in the future. At least having it `.githubutilities` so its treated like a "hidden" folder. I'm not sure what the standard naming convention is or what other projects do.

**Comment by aldebaran30701** [comment]
Easy, 
Ticket made #998 
I've pushed a commit that changes githubutilities to .githubutilities

**Review by antares1470 — APPROVED** [review]

**Pull request merged**
