### PR TITLE
Fixed a bug preventing v1 graphs from being open.

### PR DESCRIPTION
**Pull request by arcturus2**
### Description of the Change

Fixed a bug preventing v1 graphs from being open. The exception was:

```
SEVERE [global]
java.lang.ArrayIndexOutOfBoundsException: Index -1107 out of bounds for length 64
	at au.gov.asd.tac.constellation.graph.StoreGraph.getFloatValue(StoreGraph.java:1882)
	at au.gov.asd.tac.constellation.graph.visual.framework.GraphVisualAccess.getConnectionVisibility(GraphVisualAccess.java:1134)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.batcher.LineBatcher.bufferColorInfo(LineBatcher.java:258)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.batcher.LineBatcher.lambda$createBatch$1(LineBatcher.java:165)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.batcher.LineBatcher.createBatch(LineBatcher.java:161)
	at au.gov.asd.tac.constellation.visual.opengl.renderer.GraphRenderable.lambda$getChangeProcessor$4(GraphRenderable.java:178)
	at au.gov.asd.tac.constellation.utilities.visual.VisualProcessor.lambda$processChangeSet$1(VisualProcessor.java:296)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at au.gov.asd.tac.constellation.utilities.visual.VisualProcessor.lambda$processChangeSet$2(VisualProcessor.java:295)
	at java.base/java.util.HashMap.forEach(Unknown Source)
	at au.gov.asd.tac.constellation.utilities.visual.VisualProcessor.processChangeSet(VisualProcessor.java:293)
	at au.gov.asd.tac.constellation.utilities.visual.VisualProcessor.lambda$update$0(VisualProcessor.java:206)
[catch] at java.base/java.lang.Thread.run(Unknown Source)
```

### Verification Process

1. Created a graph in v1.3.1
2. Tried to open the graph in v2

### CODE REVIEW

**Comment by aldebaran30701** [comment]
Would it be better to use .ensure(wg) here? That way that attribute will be created if it does not exist?
https://github.com/constellation-app/constellation/blob/4d7ddf8d883010f9e0a238d2d3c69f43a36912a8/CoreVisualGraph/src/au/gov/asd/tac/constellation/graph/visual/framework/GraphVisualAccess.java#L606

**Comment by aldebaran30701** [comment]
I'm approving these changes, Because they fix the immediate issue. To combat the issue from the root - I've got a Pr waiting to ensure that the attributes within `StoreGraph.java` also are not effected when used with V1 graphs.

**Comment by arcturus2** [comment]
@aldebaran30701 your right. I tried to add some transactions to layer 2 and got:

```
java.lang.ArrayIndexOutOfBoundsException: Index -1107 out of bounds for length 64
	at au.gov.asd.tac.constellation.graph.StoreGraph.getIntValue(StoreGraph.java:1872)
	at au.gov.asd.tac.constellation.views.layers.utilities.UpdateElementBitmaskPlugin.setTransactions(UpdateElementBitmaskPlugin.java:77)
	at au.gov.asd.tac.constellation.views.layers.utilities.UpdateElementBitmaskPlugin.edit(UpdateElementBitmaskPlugin.java:44)
	at au.gov.asd.tac.constellation.plugins.templates.SimpleEditPlugin.describedEdit(SimpleEditPlugin.java:206)
[catch] at au.gov.asd.tac.constellation.plugins.templates.SimpleEditPlugin.run(SimpleEditPlugin.java:114)
Caused: java.lang.RuntimeException
	at au.gov.asd.tac.constellation.plugins.templates.SimpleEditPlugin.run(SimpleEditPlugin.java:134)
[catch] at au.gov.asd.tac.constellation.graph.node.plugins.DefaultPluginEnvironment.lambda$executePluginLater$0(DefaultPluginEnvironment.java:123)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I am going to have a look at this more but if you have ideas on how to support backward compatibility and allow graphs to use the Layers View that will be great!

**Comment by arcturus2** [comment]
> I'm approving these changes, Because they fix the immediate issue. To combat the issue from the root - I've got a Pr waiting to ensure that the attributes within StoreGraph.java also are not effected when used with V1 graphs.

Just saw this - awesome. Ignore my comment then.

**Pull request merged**
