### PR TITLE
Update to the horizontal toolbar

### PR DESCRIPTION
**Pull request by formalhaut69**
Replaced the horizontal toolbar icons with 2D icons

### CODE REVIEW

**Comment by arcturus2** [comment]
@formalhaut69 the icons look awesome and consistent.

image

I'm being picky now but with the blaze icons, the triangles don't have smooth edges. Can anything be done to improve that?

**Comment by formalhaut69** [comment]
> 
> 
> @formalhaut69 the icons look awesome and consistent.
> 
> image
> 
> I'm being picky now but with the blaze icons, the triangles don't have smooth edges. Can anything be done to improve that?
> 
> This is the old icons for comparison
> 
> image

@arcturus2 if I add a little shading I can smooth these edges out.

**Comment by arcturus2** [comment]
>@arcturus2 if I add a little shading I can smooth these edges out.

ok I think that would be good @formalhaut69

**Comment by formalhaut69** [comment]
image

@arcturus2 I've added some shading to make the blaze icons less pixelated.

**Pull request merged**
