### PR TITLE
Enrichment/restore default dataview categories #1919

### PR DESCRIPTION
**Pull request by Guilty-Spark-343**
### Prerequisites

- [X] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change

As mentioned in issue #1919 here is a current feature that allows the user to change the visible categories in the data view and change the order of the categories however resetting this takes some effort.  This enrichment simply adds a button, "Restore to Default",  to reset the dataview categories to the default which is all categories in the visible list in the default order.

image

### Alternate Designs

None

### Why Should This Be In Core?

This is a small change that will make the user experience better by saving time restoring to the defaults.

### Benefits

Saving time for the user to restore the categories to the default settings.

### Possible Drawbacks

None

### Verification Process

1. Open Setup > Options. Click the Constellation tab, then data access view tab.
2. Change the order of the categories and change the visible and hidden categories.
3. Click 'Restore to Default' 
4. Check the hidden categories should be empty and the visible categories should include all categories in the default order.
5. Close and Open Constellation to ensure the changes have persisted.
### Applicable Issues

#1919

### CODE REVIEW

**Review by antares1470 — CHANGES_REQUESTED** [review]
The default order being set looks a little wrong as it should be following the order of positions as specified by the positional data access plugins (e.g. see DataAccessPluginCoreType)
i.e. for Core this would be Import, Clean, Utility, Developer rather than Utility, Import, Developer, Clean

**Comment by Guilty-Spark-343** [comment]
oh good catch! The order wasn't being preserved in the HashMap.  All Fixed and good to go, thanks!

**Review by antares1470 — CHANGES_REQUESTED** [review]
Thanks @Guilty-Spark-343. Looks good now.
One thing I missed from my first review (sorry), if you could add an entry to whatsnew.txt for this, that would be great

**Comment by Guilty-Spark-343** [comment]
updated whatsnew :)

**Review by antares1470 — APPROVED** [review]

**Review by Delphinus8821 — APPROVED** [review]

**Pull request merged**
