### PR TITLE
Remove the user's time zone difference added in the Excel datetime parser

### PR DESCRIPTION
**Pull request by Auriga2**
### Prerequisites

- [ ] Reviewed the [checklist](CHECKLIST.md)

- [ ] Reviewed feedback from the "Sonar Cloud" bot. Note that you have to wait
    for the "CI / Unit Tests") to complete first. Failed Unit tests can be 
    debugged by adding the label "verbose logging" to the GitHub PR.

### Description of the Change
The dates formatted by the Excel datetime parser was introducing a time difference equal to that of the constellation user's time zone difference from GMT. This has been fixed now.

### Alternate Designs
The correct time zone details are still not included as explained in https://github.com/constellation-app/constellation/issues/1673

### Verification Process

1. Create an excel spreadsheet with a column with datetimes represented as a numeric value
2. Open File Importer in Constellation and load that file
3. Right click and set the DateTime attribute format to Datetime->EXCEL and now parse the column as a datetime
4. The same datetimes entered in the excel file should be displayed in the converted column, assuming they are in GMT

### Applicable Issues
https://github.com/constellation-app/constellation/issues/1663
https://github.com/constellation-app/constellation/pull/1668

### CODE REVIEW

**Review by arcturus2 — COMMENTED** [review]
Works well.

image

I think i am keen to see #1673 implemented soon also but for the scope of this work its working.

**Comment by antares1470** [comment]
@Auriga2 I think it would be good to add the dropdown as specified in #1673 before merging this in. The reason for that is that based on my research and understanding, excel doesn't really have a concept of timezone which means that the timezone of a datetime in excel is...whatever timezone you want it to be. That means that it is incorrect to assume that the time specified in the spreadsheet is GMT, but also incorrect to assume that it is local datetime (which is what we currently have). 

Happy for GMT to be the default option, but I think the dropdown is needed to allow users to specify the imported datetimes being of another timezone

**Comment by antares1470** [comment]
> @antares1470 There are some issues we need to discuss in #1673 I think this issue handles the original issue and now excel datetimes behave as same as Epoch datetimes (and other formats). IMO all other date time formats are also affected by this, as explained in #1673 which we can handle seperately.

@Auriga2 so I think your comments in #1673 mainly refer to the output timezone. The issues I mentioned though refer to the input timezone. The problem is that excel doesn't have a concept of timezones and so the timezone of an excel datetime is whichever timezone you want it to be. e.g. if in excel I have a cell with value 1/1/2000 12:00:00, it could be GMT, GMT-5, GMT+5 or any other timezone. That means that converting the time on its own to GMT makes no sense because you have no way of knowing what timezone you're actually converting from (as the input may not be local datetime).

Originally the ticket mentioned both epoch and excel because I didn't realise epoch is based off GMT (for some reason I had in my head it was local time) and so have removed the epoch requirement subsequently. It sounds like though that maybe there was some confusion in my wording as to what I was referring to (being able to specify the output timezone would be a nice addition though wasn't necessarily what I had in mind). I'll adjust the wording to make that more clear.

Does that make sense?

**Comment by Auriga2** [comment]
@antares1470 Yes this is exactly my point. But in my understanding there are no 2 time zones as input and output. Since Excel (And epoch) doesn't contain time zone details we will let the user specify it (in https://github.com/constellation-app/constellation/issues/1673), then we will apply it in the formatted datetime.

 If they wish to convert it into a different time zone later, they can use the attribute editor.

**Comment by antares1470** [comment]
> @antares1470 Yes this is exactly my point. But in my understanding there are no 2 time zones as input and output. Since Excel (And epoch) doesn't contain time zone details we will let the user specify it (in #1673), then we will apply it in the formatted datetime.
> 
> If they wish to convert it into a different time zone later, they can use the attribute editor.

@Auriga2 The thing with Epoch is that it is measured from an absolute point in time (1/1/1970 midnight GMT) and so the value that we import for it will be the correct time, just maybe not necessarily in the desired timezone. With Excel on the other hand, this is not the case. If I have a column of local datetimes and then import them in with the excel formatter, this current solution will import them will the same numbers but with GMT slapped on the end. This means that unless the local timezone was GMT, the data is being **incorrectly** imported as the output isn't equivalent to the input.

The purpose of #1673 is to convert a datetime to the desired timezone, not to just slap a desired timezone on the end.
e.g. `1/1/1970 0:00 GMT` could change to `1/1/1970 10:00 GMT+10`, not `1/1/1970 0:00 GMT+10`

**Comment by Auriga2** [comment]
From what I read, EPOCH is the same.

https://www.techtarget.com/searchdatacenter/definition/epoch

> What is epoch?
> In a computing context, an epoch is the date and time relative to which a computer's clock and timestamp values are determined. The epoch traditionally corresponds to 0 hours, 0 minutes, and 0 seconds (00:00:00) Coordinated Universal Time (UTC) on a specific date, which varies from system to system. Most versions of [Unix](https://www.techtarget.com/searchdatacenter/definition/Unix), for example, use January 1, 1970 as the epoch date; [Windows](https://www.techtarget.com/searchwindowsserver/definition/Windows) uses January 1, 1601; Macintosh systems use January 1, 1904, and Digital Equipment Corporation's Virtual Memory System (VMS) uses November 17, 1858.

image

 Also as I mentioned in https://github.com/constellation-app/constellation/issues/1673, the formatting adds GMT on all other formats as well. So IMO, that ticket applies to all formats not just excel.

**Comment by antares1470** [comment]
> Also as I mentioned in #1673, the formatting adds GMT on all other formats as well

Ok I didn't realise that was a thing for other timezones. I guess that means I won't make you do it here but it should definitely be addressed at some stage. I've created a ticket for it: #1698

**Review by antares1470 — APPROVED** [review]

**Review by arcturus2 — APPROVED** [review]

**Pull request merged**
